name: math2code
task_prefix: "Question: "
task_file: data/math2code/tasks.json  # JSON file with tasks
max_steps: 7
num_fewshots: 6
eval_configs:
  k_folds: 2
  k_folds_seed: 42
ai_name: Math2Code translation system
