# Math2Code 评估阶段：编程题
name: math2code
task_prefix: "Question: "
task_file: data/math2code/eval_tasks.json
max_steps: 7
num_fewshots: 6
eval_configs:
  k_folds: 2
  k_folds_seed: 42
ai_name: Math2Code translation system
